# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'desktop/window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BearFinder(object):
    def setupUi(self, BearFinder):
        BearFinder.setObjectName("BearFinder")
        BearFinder.resize(800, 600)
        BearFinder.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QtWidgets.QWidget(BearFinder)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.canvas = QtWidgets.QLabel(self.centralwidget)
        self.canvas.setText("")
        self.canvas.setObjectName("canvas")
        self.horizontalLayout.addWidget(self.canvas)
        BearFinder.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(BearFinder)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 29))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.menuView.setObjectName("menuView")
        BearFinder.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(BearFinder)
        self.statusbar.setObjectName("statusbar")
        BearFinder.setStatusBar(self.statusbar)
        self.dockWidget = QtWidgets.QDockWidget(BearFinder)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.infoText = QtWidgets.QLabel(self.dockWidgetContents)
        self.infoText.setText("")
        self.infoText.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.infoText.setObjectName("infoText")
        self.verticalLayout.addWidget(self.infoText)
        self.dockWidget.setWidget(self.dockWidgetContents)
        BearFinder.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget)
        self.actionOpen = QtWidgets.QAction(BearFinder)
        self.actionOpen.setObjectName("actionOpen")
        self.actionOpenFolder = QtWidgets.QAction(BearFinder)
        self.actionOpenFolder.setObjectName("actionOpenFolder")
        self.actionSave = QtWidgets.QAction(BearFinder)
        self.actionSave.setObjectName("actionSave")
        self.actionSaveAs = QtWidgets.QAction(BearFinder)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.actionQuit = QtWidgets.QAction(BearFinder)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionOpenFolder)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSaveAs)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(BearFinder)
        QtCore.QMetaObject.connectSlotsByName(BearFinder)

    def retranslateUi(self, BearFinder):
        _translate = QtCore.QCoreApplication.translate
        BearFinder.setWindowTitle(_translate("BearFinder", "MainWindow"))
        self.menuFile.setTitle(_translate("BearFinder", "File"))
        self.menuView.setTitle(_translate("BearFinder", "View"))
        self.actionOpen.setText(_translate("BearFinder", "Open"))
        self.actionOpenFolder.setText(_translate("BearFinder", "Open Folder"))
        self.actionSave.setText(_translate("BearFinder", "Save"))
        self.actionSaveAs.setText(_translate("BearFinder", "Save As"))
        self.actionQuit.setText(_translate("BearFinder", "Quit"))
